In [2]:
from BSDE import *
import cProfile
import warnings
warnings.filterwarnings("ignore")
import time

T = 0.5
m_time_discretization = 6
K = 100
S0 = 100
sigma = 0.2
r = 0.04
p = 7
M = np.eye(p)
N_particles = 1000
n_neighbors = 20
mu = 0.06
R = 0.06
q = 0.



for n_neighbors in range(1, N_particles, 50):
    start = time.time()
    test = BSDE(S0, K, T, mu, sigma, q)
    price_derivative = test.get_price_derivative(R, r, N_particles, 
                                                 m_time_discretization, l=1., n_neighbors=n_neighbors,
                                                 use_display=False)
    elapsed = time.time() - start
    print('With a number of {} neighbors out of \
          {} particles, we get a {} price in {}s'.format(n_neighbors, N_particles,
                                                         round(price_derivative, 4),
                                                         round(elapsed, 4)))


With a number of 1 neighbors out of           1000 particles, we get a 7.3684 price in 0.3718s
With a number of 51 neighbors out of           1000 particles, we get a 7.6832 price in 0.3827s
With a number of 101 neighbors out of           1000 particles, we get a 6.8335 price in 0.7355s
With a number of 151 neighbors out of           1000 particles, we get a 6.7985 price in 1.1315s
With a number of 201 neighbors out of           1000 particles, we get a 6.9539 price in 1.3836s
With a number of 251 neighbors out of           1000 particles, we get a 6.5908 price in 1.7697s
With a number of 301 neighbors out of           1000 particles, we get a 7.3014 price in 2.2041s
With a number of 351 neighbors out of           1000 particles, we get a 6.8753 price in 2.5879s
With a number of 401 neighbors out of           1000 particles, we get a 7.0056 price in 3.0618s
With a number of 451 neighbors out of           1000 particles, we get a 6.9892 price in 3.4422s
With a number of 501 neighbors ou

KeyboardInterrupt: 

In [3]:
#from BSDE import *
#import cProfile
#import warnings
#import bokeh
from bokeh.layouts import gridplot
from bokeh.plotting import figure, output_notebook, show
warnings.filterwarnings("ignore")
import time
%matplotlib inline

In [4]:
output_notebook()

Loading BokehJS ...

## Test with all the neighbors 

In [5]:
T = 0.5
m_time_discretization = 12
plt.rcParams['figure.figsize'] = (7*m_time_discretization,7*2)
K = 100
S0 = 100
sigma = 0.2
r = 0.04
p = 7
M = np.eye(p)
N_particles = 1000
n_neighbors = 999
mu = 0.06
R = 0.06
q = 0.
test = BSDE(S0, K, T, mu, sigma, q)
price_derivative = test.get_price_derivative(R, r, N_particles, m_time_discretization, l=1., 
                                             n_neighbors=n_neighbors,use_display=True)

print (price_derivative)

6.89378235488


## Test with 10% of neighbors 

In [6]:
T = 0.5
m_time_discretization = 12
plt.rcParams['figure.figsize'] = (7*m_time_discretization,7*2)
K = 100
S0 = 100
sigma = 0.2
r = 0.04
p = 7
M = np.eye(p)
N_particles = 1000
n_neighbors = 99
mu = 0.06
R = 0.06
q = 0.
test = BSDE(S0, K, T, mu, sigma, q)
price_derivative = test.get_price_derivative(R, r, N_particles, m_time_discretization, l=1., 
                                             n_neighbors=n_neighbors,use_display=True)

print (price_derivative)

6.73650882898


In [30]:
from sklearn.neighbors import NearestNeighbors
import numpy as np
X = np.array([[-1, -1, 1], [-2, -1, 2], [-3, -2, 1], [1, 1, 0], [2, 1, 3], [3, 2, 1]])
nbrs = NearestNeighbors(n_neighbors=5).fit(X)

In [31]:
distances, indices = nbrs.kneighbors(X)

In [32]:
X

array([[-1, -1,  1],
       [-2, -1,  2],
       [-3, -2,  1],
       [ 1,  1,  0],
       [ 2,  1,  3],
       [ 3,  2,  1]])

In [33]:
indices

array([[0, 1, 2, 3, 4],
       [1, 0, 2, 3, 4],
       [2, 1, 0, 3, 4],
       [3, 5, 0, 4, 1],
       [4, 5, 3, 0, 1],
       [5, 3, 4, 0, 1]], dtype=int64)

In [34]:
distances

array([[ 0.        ,  1.41421356,  2.23606798,  3.        ,  4.12310563],
       [ 0.        ,  1.41421356,  1.73205081,  4.12310563,  4.58257569],
       [ 0.        ,  1.73205081,  2.23606798,  5.09901951,  6.164414  ],
       [ 0.        ,  2.44948974,  3.        ,  3.16227766,  4.12310563],
       [ 0.        ,  2.44948974,  3.16227766,  4.12310563,  4.58257569],
       [ 0.        ,  2.44948974,  2.44948974,  5.        ,  5.91607978]])

In [39]:
indices.reshape(30,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [1],
       [0],
       [2],
       [3],
       [4],
       [2],
       [1],
       [0],
       [3],
       [4],
       [3],
       [5],
       [0],
       [4],
       [1],
       [4],
       [5],
       [3],
       [0],
       [1],
       [5],
       [3],
       [4],
       [0],
       [1]], dtype=int64)

In [53]:
row = np.array(list(range(6)) * 5)
W = scipy.sparse.coo_matrix((distances.reshape(30), (row, indices.reshape(30))), shape =(6, 6))

In [54]:
W

<6x6 sparse matrix of type '<class 'numpy.float64'>'
	with 30 stored elements in COOrdinate format>

In [47]:
row

array([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4,
       5, 0, 1, 2, 3, 4, 5])

In [45]:
[1, 2, 3] * 5

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]