In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import leastsq
import pandas as pd
import math
from scipy.stats import norm
from sklearn.ensemble import RandomForestRegressor
import scipy.stats as stats
from sklearn.neighbors import kneighbors_graph
import time

import scipy.sparse as sparse
from scipy.stats import multivariate_normal
import matplotlib.pyplot as plt
plt.rcParams['figure.figsize'] = (7,7) # Make the figures a bit bigger

In [3]:
x = np.array([[1,2,3,45],[3,3,5,4],[5,6,7,19]])

np.std(x, axis=1)

array([ 18.63296809,   0.8291562 ,   5.67340286])

In [9]:
len(x[0])

4

In [35]:
al = np.ndarray(shape=(4, 2))
l = np.asarray([np.array([1,2,3, 4]), x[0]], order='F')
l = l.reshape(4,2)

In [40]:
l = l.tolist()

In [42]:
x[l[0]]

array([[ 3,  3,  5,  4],
       [ 5,  6,  7, 19]])

In [38]:
nn

(array([1, 3], dtype=int32), array([0, 1], dtype=int32))

In [10]:
y[nn[1][2:4].tolist() + [5]]

array([0, 2, 5])

In [51]:
u = 3
v = 4
t = 5
y = np.zeros([u,v,t])
for i in range(5): 
    y[:, :, i] = x

In [26]:
np.log(y)

array([[[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.69314718,  0.69314718,  0.69314718,  0.69314718,  0.69314718],
        [ 1.09861229,  1.09861229,  1.09861229,  1.09861229,  1.09861229],
        [ 3.80666249,  3.80666249,  3.80666249,  3.80666249,  3.80666249]],

       [[ 1.09861229,  1.09861229,  1.09861229,  1.09861229,  1.09861229],
        [ 1.09861229,  1.09861229,  1.09861229,  1.09861229,  1.09861229],
        [ 1.60943791,  1.60943791,  1.60943791,  1.60943791,  1.60943791],
        [ 1.38629436,  1.38629436,  1.38629436,  1.38629436,  1.38629436]],

       [[ 1.60943791,  1.60943791,  1.60943791,  1.60943791,  1.60943791],
        [ 1.79175947,  1.79175947,  1.79175947,  1.79175947,  1.79175947],
        [ 1.94591015,  1.94591015,  1.94591015,  1.94591015,  1.94591015],
        [ 2.94443898,  2.94443898,  2.94443898,  2.94443898,  2.94443898]]])

In [27]:
dist_3d_matrix = -np.subtract.outer(y, y)


In [29]:
marginal_vector = np.mean(dist_3d_matrix, axis=0)

In [32]:
np.size(marginal_vector)

1200

In [33]:
nn = kneighbors_graph(x[0].reshape(4,1), 2, mode='distance').nonzero()

8.5833333333333339

In [35]:
np.mean(y, axis = 0)

array([[  3.        ,   3.        ,   3.        ,   3.        ,   3.        ],
       [  3.66666667,   3.66666667,   3.66666667,   3.66666667,
          3.66666667],
       [  5.        ,   5.        ,   5.        ,   5.        ,   5.        ],
       [ 22.66666667,  22.66666667,  22.66666667,  22.66666667,
         22.66666667]])

In [38]:
m = np.array([[1, 2], [4, 5]])
M = np.array([[0, 3], [6, 7]])

In [40]:
V = np.array([m, M])
V

array([[[1, 2],
        [4, 5]],

       [[0, 3],
        [6, 7]]])

In [44]:
m.reshape(4,1)

array([[1],
       [2],
       [4],
       [5]])

In [67]:
print(y[0, 0:2])
print(y[1,0:3])

[[ 1.  1.  1.  1.  1.]
 [ 2.  2.  2.  2.  2.]]
[[ 3.  3.  3.  3.  3.]
 [ 3.  3.  3.  3.  3.]
 [ 5.  5.  5.  5.  5.]]


In [65]:
d = np.subtract.outer(y[0, 0:2], y[1,0:3])

In [56]:
a = np.array([[1, 0], [0, 1]])

In [47]:
a[[0,1], [0,1]]

array([1, 1])

In [48]:
[0,1] + [2]

[0, 1, 2]

In [49]:
b = range(10)

In [50]:
b

range(0, 10)

In [51]:
b = list(b)

In [52]:
b

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [54]:
a[0].tolist() + list(range(2))

[1, 0, 0, 1]

In [57]:
b = a
b[1,1] = 0 
a, b

(array([[1, 0],
        [0, 0]]), array([[1, 0],
        [0, 0]]))